### PR TITLE
convert to vector before doing calculation in combine

### PR DESCRIPTION
**Pull request by chenlilyd**
In my test I found that inside `learn-step`, `m/add` is applied [here](https://github.com/cambioscience/sigmapi/blob/957e983d74e7976a77e56d7586fbdca460f34b65/src/sigmapi/core.cljc#L209), the first argument `tm` is a Clojure vector which can decrease performance.

Some benchmark test:
```
  (require
    '[clj-async-profiler.core :as prof]
    '[clojure.core.matrix :as m :refer [matrix]])

(def inputs (read-string (slurp "learn-step-inputs.edn")))

  (prof/profile
    (dotimes [_ 10]
      (time (learn-step inputs))))

  ;; with current sigmapi commit

  ;; "Elapsed time: 366.664094 msecs"
  ;; "Elapsed time: 262.04961 msecs"
  ;; "Elapsed time: 250.781755 msecs"
  ;; "Elapsed time: 257.989661 msecs"
  ;; "Elapsed time: 253.044515 msecs"
  ;; "Elapsed time: 255.892414 msecs"
  ;; "Elapsed time: 249.065483 msecs"
  ;; "Elapsed time: 255.923713 msecs"
  ;; "Elapsed time: 255.653309 msecs"
  ;; "Elapsed time: 254.62773 msecs"

  ;; After vectorizing
  ;; "Elapsed time: 224.632673 msecs"
  ;; "Elapsed time: 127.760103 msecs"
  ;; "Elapsed time: 111.955565 msecs"
  ;; "Elapsed time: 108.445775 msecs"
  ;; "Elapsed time: 111.01265 msecs"
  ;; "Elapsed time: 107.563685 msecs"
  ;; "Elapsed time: 105.83532 msecs"
  ;; "Elapsed time: 105.873592 msecs"
  ;; "Elapsed time: 107.711478 msecs"
  ;; "Elapsed time: 111.195091 msecs"

```

### CODE REVIEW

**Comment by Hendekagon** [comment]
hi - @chenlilyd did you test this using the Vectorz implementation of core.matrix ?
AFAIK, if using  `(m/set-current-implementation :vectorz)` then transposed matrices shouldn't be Clojure vectors

**Comment by chenlilyd** [comment]
We do have a `(m/set-current-implementation :vectorz)` at the beginning of our namespace in our code. 

I think `set-current-implementation` changes the underlying datastructure / type of matrix, it will not do the conversion: 

```
(m/set-current-implementation :vectorz)
(type (m/transpose (vec (range 10))))
;; =>	clojure.lang.PersistentVector

(type (m/matrix (range 10)))
;; =>	mikera.vectorz.Vector <=== 

(m/set-current-implementation :persistent-vector)
(type (m/matrix (range 10)))
;; =>	clojure.lang.PersistentVector <===
```

**Comment by Hendekagon** [comment]
"We do have a (m/set-current-implementation :vectorz) at the beginning of our namespace in our code." - in Blackbird yes, but I was asking regarding testing _this_ library on its own

ok yes,

```
(-> (m/reshape (range 27) [3 3 3]) m/matrix type)
=> mikera.arrayz.impl.SliceArray
```

but, 
```
(-> (m/reshape (range 27) [3 3 3]) m/matrix (m/transpose [2 1 0]) type)
=> clojure.lang.PersistentVector
```

which is surprising to me but I checked the core.matrix source and it looks like it only does implementation-specific transpose for the 2d case

**Comment by Hendekagon** [comment]
I had hoped to remove that transpose (see my comment in the code) as I didn't like having to do it, wishing it could be done only with broadcasting.

**Comment by Hendekagon** [comment]
@chenlilyd I don't understand why you're doing `(not (instance? Vector tm))` in there -- `tm` is the transposed matrix, it will never be a `mikera.vectorz.Vector`, though it could be a `mikera.matrixx.Matrix`

**Comment by Hendekagon** [comment]
also probably best to keep it implementation-independent

**Comment by chenlilyd** [comment]
My update is based on flamegraph from profiling `learn-step`, I admit I have very limited knowledge on this library and the matrix vectorz libraries. I'll take a closer look later. Thanks @Hendekagon

**Comment by Hendekagon** [comment]
profiling without and with the change after the transpose:

```
; without converting to m/matrix after the transpose
(quick-bench (MHP {:correct-door (rand-int 3) :choose-door (rand-int 3)}))
Evaluation count : 480 in 6 samples of 80 calls.
             Execution time mean : 1.353044 ms
    Execution time std-deviation : 70.165858 µs
   Execution time lower quantile : 1.290250 ms ( 2.5%)
   Execution time upper quantile : 1.452780 ms (97.5%)
                   Overhead used : 2.023449 ns

; with m/matrix after transpose
Loading src/sigmapi/core.cljc... done
(quick-bench (MHP {:correct-door (rand-int 3) :choose-door (rand-int 3)}))
Evaluation count : 696 in 6 samples of 116 calls.
             Execution time mean : 929.232114 µs
    Execution time std-deviation : 52.757466 µs
   Execution time lower quantile : 887.015578 µs ( 2.5%)
   Execution time upper quantile : 1.006789 ms (97.5%)
                   Overhead used : 2.023449 ns
```
not much in it -- and according to Tufte:

```
"pId                                           nCalls        Min      50% ≤      90% ≤      95% ≤      99% ≤        Max       Mean   MAD      Clock  Total
 
 :clojure.core.matrix/transpose                    48    14.63μs    43.83μs    75.38μs    81.63μs   130.42μs   130.42μs    43.68μs  ±44%     2.10ms    14%
 :clojure.core.matrix/matrix                       64    13.13μs    29.25μs    51.13μs    70.21μs   118.50μs   153.42μs    32.51μs  ±47%     2.08ms    14%
 :clojure.core.matrix/array                        64    11.17μs    27.04μs    48.75μs    68.54μs   115.29μs   143.08μs    30.31μs  ±49%     1.94ms    13%
 :clojure.core.matrix/add                          71   208.00ns    14.83μs    42.17μs    55.38μs    71.75μs    92.25μs    19.39μs  ±69%     1.38ms     9%
 :clojure.core.matrix/emap                         53     3.67μs    11.54μs    25.63μs    32.38μs    38.21μs    59.00μs    14.79μs  ±55%   784.08μs     5%
 :clojure.core.matrix/index-seq                    35     4.21μs     6.79μs    12.46μs    17.54μs   149.92μs   149.92μs    11.99μs  ±71%   419.66μs     3%
 :clojure.core.matrix/index-seq-for-shape          35     2.25μs     4.33μs     9.75μs    10.46μs   146.58μs   146.58μs     9.26μs  ±88%   324.17μs     2%
 :clojure.core.matrix/mget                         92   583.00ns   917.00ns     2.17μs     2.92μs     4.96μs     7.42μs     1.25μs  ±45%   115.33μs     1%
 :clojure.core.matrix/implementation-check         64     1.08μs     1.63μs     1.83μs     2.08μs     2.83μs     6.38μs     1.69μs  ±16%   108.13μs     1%
 :clojure.core.matrix/esum                         40   667.00ns     1.46μs     3.42μs     3.67μs     8.33μs     8.33μs     1.83μs  ±52%    73.08μs     1%
 :clojure.core.matrix/slices                       26   708.00ns   792.00ns     1.00μs     1.21μs     4.50μs     4.50μs   971.12ns  ±30%    25.25μs     0%
 :clojure.core.matrix/emin                         18   750.00ns   833.00ns     1.83μs     2.50μs     3.83μs     3.83μs     1.26μs  ±48%    22.75μs     0%
 
 Accounted                                                                                                                                   9.37ms    64%
 Clock                                                                                                                                      14.58ms   100%
 "
 ```
 
 `transpose` takes most of the time if we convert back to matrix after, because Vectorz doesn't support general transpose, so while converting to matrix pays for itself later for the m/add operation (which is what sigmapi is doing most of the time, as it's mostly element-wise multiplying) it loses on the transpose.
 If we were using a different implementation (BLAS or nd4j) this might not be an issue but for now we have to use Vectorz, so I think the best thing is for me to find a way to remove the transpose operation, meanwhile making this change doesn't hurt but let's keep it implementation-independent.

**Pull request merged**
